# Generated by Django 5.0 on 2024-01-23 02:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('custom_id', models.CharField(default='', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('about', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('interview_time', models.DateTimeField(blank=True, null=True)),
                ('interviewed', models.BooleanField(default=False)),
                ('dept_choice', models.CharField(blank=True, max_length=200, null=True)),
                ('drive_link', models.CharField(blank=True, max_length=200, null=True)),
                ('semester', models.CharField(default='spring2049', max_length=100)),
                ('assigned_department', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='applicant',
            constraint=models.UniqueConstraint(fields=('user', 'semester'), name='unique_user_semester'),
        ),
    ]
