# Generated by Django 5.0 on 2024-01-30 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntraEventFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('segment_name', models.CharField(max_length=200)),
                ('team_member_name_1', models.CharField(max_length=100)),
                ('team_member_student_id_1', models.CharField(max_length=20)),
                ('is_robu_member_1', models.BooleanField(default=False)),
                ('robu_dept_1', models.CharField(blank=True, max_length=100, null=True)),
                ('gsuit_1', models.CharField(blank=True, max_length=100, null=True)),
                ('team_member_name_2', models.CharField(max_length=100)),
                ('team_member_student_id_2', models.CharField(max_length=20)),
                ('is_robu_member_2', models.BooleanField(default=False)),
                ('robu_dept_2', models.CharField(blank=True, max_length=100, null=True)),
                ('gsuit_2', models.CharField(blank=True, max_length=100, null=True)),
                ('team_member_name_3', models.CharField(max_length=100)),
                ('team_member_student_id_3', models.CharField(max_length=20)),
                ('is_robu_member_3', models.BooleanField(default=False)),
                ('robu_dept_3', models.CharField(blank=True, max_length=100, null=True)),
                ('gsuit_3', models.CharField(blank=True, max_length=100, null=True)),
                ('team_member_name_4', models.CharField(max_length=100)),
                ('team_member_student_id_4', models.CharField(max_length=20)),
                ('is_robu_member_4', models.BooleanField(default=False)),
                ('robu_dept_4', models.CharField(blank=True, max_length=100, null=True)),
                ('gsuit_4', models.CharField(blank=True, max_length=100, null=True)),
                ('team_member_name_5', models.CharField(max_length=100)),
                ('team_member_student_id_5', models.CharField(max_length=20)),
                ('is_robu_member_5', models.BooleanField(default=False)),
                ('robu_dept_5', models.CharField(blank=True, max_length=100, null=True)),
                ('gsuit_5', models.CharField(blank=True, max_length=100, null=True)),
                ('team_member_name_6', models.CharField(max_length=100)),
                ('team_member_student_id_6', models.CharField(max_length=20)),
                ('is_robu_member_6', models.BooleanField(default=False)),
                ('robu_dept_6', models.CharField(blank=True, max_length=100, null=True)),
                ('gsuit_6', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='intraeventformsubmission',
            constraint=models.UniqueConstraint(fields=('user', 'event_name', 'segment_name'), name='unique_user_event_segment'),
        ),
    ]
