# Generated by Django 5.0 on 2024-01-02 12:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CreatedModel',
        ),
        migrations.RemoveField(
            model_name='department',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='department',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='student',
        ),
        migrations.AddField(
            model_name='applicant',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='applicant',
            name='drive_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='semester',
            field=models.CharField(default='spring2049', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(default='not selected', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='interview_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='forms.applicant'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='dept_choice',
            field=models.ManyToManyField(blank=True, to='forms.dept'),
        ),
        migrations.AddConstraint(
            model_name='applicant',
            constraint=models.UniqueConstraint(fields=('user', 'semester'), name='unique_user_semester'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='DeptChoice',
        ),
    ]
