# Generated by Django 5.0 on 2024-01-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_intraeventformsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intraeventformsubmission',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intraeventformsubmission',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='intraeventformsubmission',
            name='team_member_name_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intraeventformsubmission',
            name='team_member_name_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intraeventformsubmission',
            name='team_member_name_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intraeventformsubmission',
            name='team_member_name_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intraeventformsubmission',
            name='team_member_name_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intraeventformsubmission',
            name='team_member_student_id_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='intraeventformsubmission',
            name='team_member_student_id_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='intraeventformsubmission',
            name='team_member_student_id_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='intraeventformsubmission',
            name='team_member_student_id_5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='intraeventformsubmission',
            name='team_member_student_id_6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
