# Generated by Django 5.0 on 2024-01-02 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_dept_delete_createdmodel_remove_department_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
