# Generated by Django 5.0 on 2024-01-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_applicant_application_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='project',
            new_name='user',
        ),
    ]
