# Generated by Django 5.0 on 2024-04-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_intraeventformsubmission_unique_user_event_segment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeedbackExternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('participant', models.BooleanField(default=False)),
                ('sentiment', models.CharField(max_length=10)),
                ('text', models.TextField()),
            ],
        ),
    ]
