# Generated by Django 5.0 on 2024-01-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_applicant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='dept_choice',
        ),
        migrations.DeleteModel(
            name='Dept',
        ),
        migrations.AddField(
            model_name='applicant',
            name='dept_choice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
