# Generated by Django 5.0 on 2024-01-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_remove_applicant_dept_choice_delete_dept_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='id',
        ),
        migrations.AddField(
            model_name='applicant',
            name='custom_id',
            field=models.CharField(default='', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
