# Generated by Django 5.0 on 2024-01-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_remove_applicant_id_applicant_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='assigned_department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
