# Generated by Django 5.0 on 2024-01-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_applicant_assigned_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
