# Generated by Django 5.0 on 2024-01-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_applicant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
